"""State definitions for LangGraph agentic workflows.

This module defines the central `AgentState` TypedDict used by LangGraph to maintain state
across conversation turns, execution steps, dataset metadata, and planning traces.
"""

from __future__ import annotations

from typing import Annotated, TypedDict

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages

from csv_analytics_agent.graph.checkpoint import AnalysisResultCheckpoint, JSONValue
from csv_analytics_agent.profiler.models import DatasetProfile

# Precise type aliases avoiding untyped Any
FilterValue = str | int | float | list[str] | list[int] | list[float]
FilterPayload = dict[str, FilterValue]
MetadataValue = JSONValue

# Router decision dictionary type alias for state propagation
RouterDecisionDict = dict[str, str | float | dict[str, str | int | float | bool]]


class AgentState(TypedDict, total=False):
    """LangGraph state contract for CSV Analytics Agent workflows.

    Attributes:
        messages: Conversation message history managed with LangGraph's add_messages reducer.
        profile: JSON-compatible DatasetProfile representation.
        dataset_hash: Cryptographic SHA-256 hash string identifying the dataset state.
        active_filters: List of active filter condition dictionary payloads.
        last_analysis_result: Bounded artifact metadata; payloads remain runtime-only.
        retrieved_columns: Column names relevant to the active user question.
        iteration_count: Number of graph node execution iterations completed.
        planner_result: Latest PlannerResult generated by Stage 6 RulePlanner or LLM Planner.
        router_decision: Deterministic router classification propagated to downstream nodes.
        thread_id: Unique conversation thread identifier for checkpoint persistence.
        metadata: Additional context metadata dictionary.
    """

    messages: Annotated[list[BaseMessage], add_messages]
    profile: dict[str, JSONValue] | None
    dataset_hash: str | None
    active_filters: list[FilterPayload]
    last_analysis_result: AnalysisResultCheckpoint | None
    retrieved_columns: list[str]
    iteration_count: int
    planner_result: dict[str, JSONValue] | None
    router_decision: RouterDecisionDict | None
    thread_id: str | None
    executed_tools: list[str]
    metadata: dict[str, MetadataValue]


def create_initial_state(
    profile: DatasetProfile | None = None,
    thread_id: str | None = None,
) -> AgentState:
    """Helper utility to construct a clean initial AgentState dictionary.

    Args:
        profile: Optional profile converted at this boundary to JSON-compatible data.
        thread_id: Optional initial thread identifier.

    Returns:
        Freshly populated AgentState dictionary.
    """
    return AgentState(
        messages=[],
        profile=profile.model_dump(mode="json") if profile is not None else None,
        dataset_hash=None,
        active_filters=[],
        last_analysis_result=None,
        retrieved_columns=[],
        iteration_count=0,
        planner_result=None,
        router_decision=None,
        thread_id=thread_id,
        executed_tools=[],
        metadata={},
    )


__all__ = [
    "AgentState",
    "FilterPayload",
    "FilterValue",
    "MetadataValue",
    "RouterDecisionDict",
    "create_initial_state",
]
