"""State definitions for LangGraph agentic workflows.

This module defines the central `AgentState` TypedDict used by LangGraph to maintain state
across conversation turns, execution steps, dataset metadata, and planning traces.
"""

from __future__ import annotations

from typing import Annotated, TypedDict

import pandas as pd
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages

from csv_analytics_agent.execution.models import ExecutionResult
from csv_analytics_agent.graph.models import PlannerResult
from csv_analytics_agent.profiler.models import DatasetProfile
from csv_analytics_agent.results.models import AnalysisResult

# Precise type aliases avoiding untyped Any
FilterValue = str | int | float | list[str] | list[int] | list[float]
FilterPayload = dict[str, FilterValue]
MetadataValue = str | int | float | bool


class AgentState(TypedDict, total=False):
    """LangGraph state contract for CSV Analytics Agent workflows.

    Attributes:
        messages: Conversation message history managed with LangGraph's add_messages reducer.
        working_df: Active in-memory pandas DataFrame currently loaded and analyzed.
        profile: Immutable DatasetProfile containing row counts, missing ratios, and column stats.
        dataset_hash: Cryptographic SHA-256 hash string identifying the dataset state.
        active_filters: List of filter condition dictionary payloads applied to working_df.
        last_result: Latest ExecutionResult payload returned by Stage 5 Execution Framework.
        last_analysis_result: Latest unified AnalysisResult payload from Stage 8.6.
        retrieved_columns: Column names relevant to the active user question.
        iteration_count: Number of graph node execution iterations completed.
        planner_result: Latest PlannerResult generated by Stage 6 RulePlanner or LLM Planner.
        thread_id: Unique conversation thread identifier for checkpoint persistence.
        metadata: Additional context metadata dictionary.
    """

    messages: Annotated[list[BaseMessage], add_messages]
    working_df: pd.DataFrame | None
    profile: DatasetProfile | None
    dataset_hash: str | None
    active_filters: list[FilterPayload]
    last_result: ExecutionResult | None
    last_analysis_result: AnalysisResult | None
    retrieved_columns: list[str]
    iteration_count: int
    planner_result: PlannerResult | None
    thread_id: str | None
    executed_tools: list[str]
    chart_bytes: bytes | None
    metadata: dict[str, MetadataValue]


def create_initial_state(
    working_df: pd.DataFrame | None = None,
    profile: DatasetProfile | None = None,
    thread_id: str | None = None,
) -> AgentState:
    """Helper utility to construct a clean initial AgentState dictionary.

    Args:
        working_df: Optional initial pandas DataFrame.
        profile: Optional initial DatasetProfile.
        thread_id: Optional initial thread identifier.

    Returns:
        Freshly populated AgentState dictionary.
    """
    return AgentState(
        messages=[],
        working_df=working_df,
        profile=profile,
        dataset_hash=None,
        active_filters=[],
        last_result=None,
        last_analysis_result=None,
        retrieved_columns=[],
        iteration_count=0,
        planner_result=None,
        thread_id=thread_id,
        executed_tools=[],
        chart_bytes=None,
        metadata={},
    )


__all__ = [
    "AgentState",
    "FilterPayload",
    "FilterValue",
    "MetadataValue",
    "create_initial_state",
]
