"""Tool Execution Node for executing tool calls generated by LLM Planner."""

from __future__ import annotations

import json
from typing import Any

import pandas as pd
from langchain_core.messages import AIMessage, BaseMessage, ToolMessage

from csv_analytics_agent.execution.exceptions import CapabilityNotFoundError
from csv_analytics_agent.execution.models import (
    ExecutionRequest,
    ExecutionResult,
    ExecutionStatus,
)
from csv_analytics_agent.execution.registry import CapabilityRegistry
from csv_analytics_agent.graph.checkpoint import RuntimeArtifactStore, analysis_result_to_checkpoint
from csv_analytics_agent.graph.state import AgentState, FilterPayload
from csv_analytics_agent.llm.python_generator import BasePythonCodeGenerator
from csv_analytics_agent.logging_config import get_logger
from csv_analytics_agent.profiler.models import DatasetProfile
from csv_analytics_agent.python_engine.base import BasePythonExecutor
from csv_analytics_agent.results.converters import (
    deterministic_result_to_analysis_result,
    python_result_to_analysis_result,
)
from csv_analytics_agent.results.models import AnalysisResult

logger = get_logger(__name__)


def tool_node(
    state: AgentState,
    registry: CapabilityRegistry,
    dataframe: pd.DataFrame,
    python_generator: BasePythonCodeGenerator | None = None,
    python_executor: BasePythonExecutor | None = None,
    artifact_store: RuntimeArtifactStore | None = None,
) -> dict[str, Any]:
    """LangGraph node executing tool calls generated by the LLM planner.

    Args:
        state: Active AgentState containing conversation messages and active_filters.
        registry: CapabilityRegistry instance containing registered domain engines.
        dataframe: Target dataset pandas DataFrame context.
        python_generator: Optional BasePythonCodeGenerator instance for python_analysis tool.
        python_executor: Optional BasePythonExecutor instance for python_analysis tool.
        artifact_store: Optional runtime-only store for heavy artifact payloads.

    Returns:
        Partial AgentState dictionary update containing emitted ToolMessages,
        checkpoint-safe last_analysis_result metadata, and updated active_filters.
    """
    messages: list[BaseMessage] = state.get("messages", [])
    if not messages:
        return {}

    # Find the latest AIMessage with tool calls
    last_ai_msg: AIMessage | None = None
    for msg in reversed(messages):
        if isinstance(msg, AIMessage) and getattr(msg, "tool_calls", None):
            last_ai_msg = msg
            break

    if not last_ai_msg or not last_ai_msg.tool_calls:
        return {}

    tool_messages: list[ToolMessage] = []
    last_analysis_result: AnalysisResult | None = None
    active_filters: list[FilterPayload] = list(state.get("active_filters", []))
    executed_tools: list[str] = list(state.get("executed_tools", []))

    # Execute requested tool calls sequentially preserving order
    for call in last_ai_msg.tool_calls:
        call_id = str(call.get("id", "call_unknown"))
        cap_name = str(call.get("name", ""))
        args = dict(call.get("args", {}))

        target_columns = list(args.get("target_columns", []))
        parameters = dict(args.get("parameters", {}))

        # Handle top-level argument payload parameters if nested 'parameters' is omitted
        for k, v in args.items():
            if k not in ("target_columns", "parameters"):
                parameters[k] = v

        if cap_name == "python_analysis" and python_generator and python_executor:
            question = str(args.get("question", ""))
            try:
                py_req = python_generator.generate(
                    question=question,
                    schema=(
                        DatasetProfile.model_validate(state["profile"])
                        if state.get("profile") is not None
                        else None
                    ),
                    retrieved_columns=state.get("retrieved_columns"),
                    dataset_hash=state.get("dataset_hash"),
                )
                py_res = python_executor.execute(py_req, dataframe)
                last_analysis_result = python_result_to_analysis_result(
                    py_res, question=question, dataset_hash=state.get("dataset_hash")
                )
                from csv_analytics_agent.python_engine.tool import serialize_execution_result

                tool_content = serialize_execution_result(py_res)
            except Exception as err:
                last_analysis_result = AnalysisResult.failure(
                    error_type=type(err).__name__,
                    error_message=str(err),
                    source="python_engine",
                    question=question,
                )
                tool_content = json.dumps({"success": False, "error": str(err)})

            tool_msg = ToolMessage(content=tool_content, tool_call_id=call_id)
            tool_messages.append(tool_msg)
            if cap_name not in executed_tools:
                executed_tools.append(cap_name)
            continue

        context_metadata: dict[str, Any] = {
            "profile": state.get("profile"),
            "dataset_hash": state.get("dataset_hash"),
        }

        try:
            engine = registry.get_engine(cap_name)
            request = ExecutionRequest(
                capability_name=cap_name,
                target_columns=target_columns,
                parameters=parameters,
                context_metadata=context_metadata,
            )
            exec_res = engine.execute_capability(request, dataframe)
        except CapabilityNotFoundError as err:
            logger.warning(
                "tool_call_failed",
                tool=cap_name,
                error_type="CapabilityNotFoundError",
                error=str(err),
            )
            exec_res = ExecutionResult(
                capability_name=cap_name,
                status=ExecutionStatus.FAILED,
                message=str(err),
                data=None,
            )
        except Exception as err:
            logger.warning(
                "tool_call_failed",
                tool=cap_name,
                error_type=type(err).__name__,
                error=str(err),
            )
            exec_res = ExecutionResult(
                capability_name=cap_name,
                status=ExecutionStatus.FAILED,
                message=f"Execution exception: {err}",
                data=None,
            )

        last_msg = state.get("messages", [])[-1] if state.get("messages") else None
        last_question = getattr(last_msg, "content", None) if last_msg else None
        question_str = str(last_question) if isinstance(last_question, str) else None

        last_analysis_result = deterministic_result_to_analysis_result(
            exec_res,
            capability_name=cap_name,
            question=question_str,
            dataset_hash=state.get("dataset_hash"),
        )
        if cap_name and cap_name not in executed_tools:
            executed_tools.append(cap_name)

        logger.info(
            "tool_call_result",
            tool=cap_name,
            status=exec_res.status.value,
            success=exec_res.status == ExecutionStatus.SUCCESS,
        )

        # Serialize result payload for ToolMessage content
        tool_content = json.dumps(
            {
                "capability": exec_res.capability_name,
                "status": exec_res.status.value,
                "message": exec_res.message,
                "data": str(exec_res.data)
                if not isinstance(exec_res.data, bytes)
                else f"<PNG image bytes: {len(exec_res.data)} bytes>",
            }
        )

        tool_msg = ToolMessage(content=tool_content, tool_call_id=call_id)
        tool_messages.append(tool_msg)

        # Update active_filters if filter capability succeeded
        if cap_name == "filter" and exec_res.status == ExecutionStatus.SUCCESS:
            filter_item: FilterPayload = {
                "capability": "filter",
                "target_columns": target_columns,
                "parameters": str(parameters),
            }
            active_filters.append(filter_item)

    runtime_artifact_store = artifact_store or RuntimeArtifactStore()
    checkpoint_result = (
        analysis_result_to_checkpoint(last_analysis_result, runtime_artifact_store)
        if last_analysis_result is not None
        else None
    )
    state_update: dict[str, Any] = {
        "messages": tool_messages,
        "last_analysis_result": checkpoint_result,
        "active_filters": active_filters,
        "executed_tools": executed_tools,
    }
    return state_update


__all__ = ["tool_node"]
