"""Visualization recommender orchestrator.

This module provides the main entry point to evaluate dataset profiles across all
analytical recommendation rules, rank candidates, and produce a unified VisualizationPlan.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from csv_analytics_agent.profiler.models import DatasetProfile
from csv_analytics_agent.visualization.exceptions import NoSuitableVisualizationError
from csv_analytics_agent.visualization.models import (
    ChartSpecification,
    ChartType,
    VisualizationPlan,
)
from csv_analytics_agent.visualization.rules import (
    recommend_categorical_rules,
    recommend_distribution_rules,
    recommend_relationship_rules,
    recommend_temporal_rules,
)

if TYPE_CHECKING:
    from csv_analytics_agent.insights.models import Insight

# Deterministic chart priority order for ranking recommendations
CHART_TYPE_PRIORITY: dict[ChartType, int] = {
    ChartType.LINE: 0,
    ChartType.SCATTER: 1,
    ChartType.BAR: 2,
    ChartType.HISTOGRAM: 3,
    ChartType.HEATMAP: 4,
    ChartType.BOXPLOT: 5,
    ChartType.PIE: 6,
}


def recommend_visualizations(
    profile: DatasetProfile,
    insights: list[Insight] | None = None,
) -> VisualizationPlan:
    """Generate a ranked VisualizationPlan for a dataset profile.

    Evaluates temporal, relationship, categorical, and distribution rules on dataset
    metadata, ranks non-empty specifications, and assigns the top recommendation
    as primary and remaining candidates as alternatives.

    Args:
        profile: Complete immutable dataset profile.
        insights: Optional list of insights generated by Insights Engine for future scoring.

    Returns:
        VisualizationPlan containing primary and alternative chart specifications.

    Raises:
        NoSuitableVisualizationError: If no chart specifications could be recommended.
    """
    candidates: list[ChartSpecification] = []

    candidates.extend(recommend_temporal_rules(profile))
    candidates.extend(recommend_relationship_rules(profile))
    candidates.extend(recommend_categorical_rules(profile))
    candidates.extend(recommend_distribution_rules(profile))

    if not candidates:
        raise NoSuitableVisualizationError(
            "No suitable chart specifications could be recommended for "
            "the provided dataset profile."
        )

    # Deduplicate candidates by chart_type and primary x_axis column
    seen_keys: set[tuple[ChartType, str]] = set()
    unique_candidates: list[ChartSpecification] = []
    for spec in candidates:
        key = (spec.chart_type, spec.x_axis.column)
        if key not in seen_keys:
            seen_keys.add(key)
            unique_candidates.append(spec)

    # Rank candidates by priority order
    ranked_specs = sorted(
        unique_candidates,
        key=lambda s: CHART_TYPE_PRIORITY.get(s.chart_type, 99),
    )

    primary = ranked_specs[0]
    alternatives = ranked_specs[1:]

    return VisualizationPlan(primary=primary, alternatives=alternatives)
