"""Abstract base classes for vector storage and embedding providers."""

from __future__ import annotations

from abc import ABC, abstractmethod
from pathlib import Path

from csv_analytics_agent.memory.models import (
    MemoryMetadata,
    MemoryRecord,
    MemorySearchResult,
)


class BaseEmbeddingProvider(ABC):
    """Abstract interface for generating vector embeddings from text."""

    @abstractmethod
    def embed_text(self, text: str) -> list[float]:
        """Embed a single text string into a vector float list.

        Args:
            text: Plain text input string.

        Returns:
            Vector embedding as list of floats.
        """
        ...

    @abstractmethod
    def embed_documents(self, texts: list[str]) -> list[list[float]]:
        """Embed a batch of text strings into vector float lists.

        Args:
            texts: List of text input strings.

        Returns:
            List of vector embeddings as float lists.
        """
        ...

    @property
    @abstractmethod
    def dimension(self) -> int:
        """Return dimension length of vector embeddings generated by provider."""
        ...

    @property
    @abstractmethod
    def model_name(self) -> str:
        """Return identifier string of underlying embedding model."""
        ...


class BaseVectorStore(ABC):
    """Abstract interface for vector similarity search engines."""

    @abstractmethod
    def add(self, records: list[MemoryRecord]) -> list[str]:
        """Add memory records to vector index.

        Args:
            records: List of MemoryRecord objects containing embeddings.

        Returns:
            List of record IDs successfully added.
        """
        ...

    @abstractmethod
    def search(self, query_vector: list[float], top_k: int = 5) -> list[MemorySearchResult]:
        """Perform vector similarity search against index.

        Args:
            query_vector: Query embedding float list.
            top_k: Number of nearest neighbor results to return.

        Returns:
            List of MemorySearchResult instances sorted by similarity score.
        """
        ...

    @abstractmethod
    def delete(self, record_ids: list[str]) -> None:
        """Remove records from vector store by record ID.

        Args:
            record_ids: List of record ID strings to remove.
        """
        ...

    @abstractmethod
    def clear(self) -> None:
        """Clear all records and reset vector index."""
        ...

    @abstractmethod
    def count(self) -> int:
        """Return total number of active records stored in vector index."""
        ...

    @abstractmethod
    def persist(self, path: Path | str) -> None:
        """Persist vector index and records to filesystem path.

        Args:
            path: Directory or file path for persistence.
        """
        ...

    @abstractmethod
    def load(self, path: Path | str) -> None:
        """Load vector index and records from filesystem path.

        Args:
            path: Directory or file path to load from.
        """
        ...

    @property
    @abstractmethod
    def metadata(self) -> MemoryMetadata:
        """Return collection metadata describing vector store state."""
        ...


__all__ = [
    "BaseEmbeddingProvider",
    "BaseVectorStore",
]
