"""Domain models for Python Execution Engine Interface."""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator


class PythonArtifactType(str, Enum):
    """Supported artifact types produced by Python execution."""

    TEXT = "text"
    SCALAR = "scalar"
    TABLE = "table"
    DATAFRAME = "dataframe"
    IMAGE = "image"
    INTERACTIVE = "interactive"
    DIAGRAM = "diagram"
    FILE = "file"
    UNKNOWN = "unknown"


class PythonExecutionRequest(BaseModel):
    """Payload representing a request to execute generated Python code.

    Attributes:
        code: Generated Python source code string.
        question: Original natural language user query.
        dataset_hash: Optional SHA-256 hash of target dataset.
        timeout_seconds: Maximum execution duration in seconds.
        max_output_bytes: Maximum allowed stdout/stderr and artifact payload size in bytes.
        metadata: Execution context metadata dictionary.
    """

    model_config = ConfigDict(frozen=True)

    code: str = Field(..., description="Generated Python source code string.")
    question: str = Field(..., description="Original user analytical question.")
    dataset_hash: str | None = Field(default=None, description="SHA-256 hash of target dataset.")
    timeout_seconds: float = Field(
        default=30.0,
        description="Maximum execution timeout in seconds.",
    )
    max_output_bytes: int = Field(
        default=10_000_000,
        description="Maximum output size limit in bytes.",
    )
    metadata: dict[str, str | int | float | bool] = Field(
        default_factory=dict,
        description="Arbitrary execution context metadata.",
    )

    @field_validator("code", "question")
    @classmethod
    def _validate_non_empty(cls, value: str) -> str:
        if not value or not value.strip():
            raise ValueError("Field must not be empty or whitespace-only.")
        return value

    @field_validator("timeout_seconds")
    @classmethod
    def _validate_timeout(cls, value: float) -> float:
        if value <= 0:
            raise ValueError("timeout_seconds must be greater than 0.")
        return value

    @field_validator("max_output_bytes")
    @classmethod
    def _validate_max_output_bytes(cls, value: int) -> int:
        if value <= 0:
            raise ValueError("max_output_bytes must be greater than 0.")
        return value


class PythonArtifact(BaseModel):
    """Represents a single output artifact generated by Python execution.

    Attributes:
        artifact_type: Classification category of the artifact.
        name: Descriptive name or title identifier.
        mime_type: Optional MIME media type string.
        data: Payload data (Any type allowed for DataFrames, Plotly dicts, bytes, etc.).
        metadata: Artifact metadata dictionary.
    """

    model_config = ConfigDict(frozen=True, arbitrary_types_allowed=True)

    artifact_type: PythonArtifactType = Field(..., description="Artifact category enum.")
    name: str = Field(..., description="Artifact name identifier.")
    mime_type: str | None = Field(default=None, description="Optional MIME media type.")
    data: Any = Field(
        ...,
        description="Artifact payload (DataFrames, Plotly specs, raw bytes, scalars, etc.).",
    )
    metadata: dict[str, str | int | float | bool] = Field(
        default_factory=dict,
        description="Artifact metadata key-value pairs.",
    )

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value: str) -> str:
        if not value or not value.strip():
            raise ValueError("name must not be empty or whitespace-only.")
        return value


class PythonExecutionResult(BaseModel):
    """Normalized output payload returned after executing Python code.

    Attributes:
        success: Whether execution completed without unhandled errors.
        stdout: Captured standard output stream string.
        stderr: Captured standard error stream string.
        artifacts: List of produced PythonArtifact objects.
        execution_time_ms: Duration of execution in milliseconds.
        error_type: Optional name string of caught exception type.
        error_message: Optional error message details.
        metadata: Execution outcome metadata dictionary.
    """

    model_config = ConfigDict(frozen=True)

    success: bool = Field(..., description="Whether execution succeeded.")
    stdout: str = Field(default="", description="Captured standard output.")
    stderr: str = Field(default="", description="Captured standard error.")
    artifacts: list[PythonArtifact] = Field(
        default_factory=list,
        description="List of produced PythonArtifact objects.",
    )
    execution_time_ms: float = Field(
        default=0.0,
        description="Execution duration in milliseconds.",
    )
    error_type: str | None = Field(default=None, description="Error type string if failed.")
    error_message: str | None = Field(default=None, description="Error details string if failed.")
    metadata: dict[str, str | int | float | bool] = Field(
        default_factory=dict,
        description="Outcome metadata.",
    )

    @field_validator("execution_time_ms")
    @classmethod
    def _validate_execution_time(cls, value: float) -> float:
        if value < 0:
            raise ValueError("execution_time_ms must be non-negative.")
        return value


__all__ = [
    "PythonArtifact",
    "PythonArtifactType",
    "PythonExecutionRequest",
    "PythonExecutionResult",
]
